name: Deploy to Cloud Functions

permissions:
  id-token: write
on:
  workflow_dispatch:
jobs: # Sequence of jobs for this workflow
  deploy: # Name of the job
    runs-on: ubuntu-latest # Specify virtual machine for running the job
    steps: # Sequence of steps for this job
    - name: 'Checkout' # Checkout repo to virtual machine
      uses: 'actions/checkout@v3'

    - name: 'Google auth' # Authenticate with GCP
      id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
        service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'
    - name: Deploy hello_world_function # Deploy using gcloud functions
      run: |
        gcloud run jobs deploy job-quickstart \
        --source cloud_functions/hello_world \
        --tasks 1 \
        --set-env-vars SLEEP_MS=10000 \
        --set-env-vars FAIL_RATE=0.1 \
        --max-retries 5 \
        --region  europe-west1 \
        --project="n8ns-468521"

        
