name: Deploy to Cloud Functions

permissions:
  contents: read
  id-token: write

on:
  workflow_dispatch:

jobs: # Sequence of jobs for this workflow
  deploy: # Name of the job
    runs-on: ubuntu-latest # Specify virtual machine for running the job
    steps: # Sequence of steps for this job
    - name: 'Checkout' # Checkout repo to virtual machine
      uses: 'actions/checkout@v4'

    - name: Show GitHub OIDC-relevant context
      run: |
        echo "repository=${{ github.repository }}"
        echo "ref=${{ github.ref }}"
        echo "ref_name=${{ github.ref_name }}"
        echo "actor=${{ github.actor }}"

    - name: 'Google auth' # Authenticate with GCP
      id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
        service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'
        create_credentials_file: true

    - name: Set up gcloud SDK
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        project_id: 'n8ns-468521'

    - name: Deploy hello_world_function # Deploy using gcloud functions
      run: |
        gcloud run jobs deploy job-quickstart \
        --source cloud_functions/hello_world \
        --tasks 1 \
        --set-env-vars SLEEP_MS=10000 \
        --set-env-vars FAIL_RATE=0.1 \
        --max-retries 5 \
        --region  europe-west1 \
        --project="n8ns-468521"

        
